language: rust
cache: cargo
rust:
  - nightly
  - beta
  - stable
  - 1.24.1
before_script:
  - sudo chmod -R 0777 /home/travis/build/kosinix/raster/tests/
script:
  - cargo build
  - cargo test
  - cargo doc
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy-docs.sh
